name: 'CI Test Runner'
on:
  pull_request:
  workflow_dispatch:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4         
      
      - run: npm ci                       
      
      - run: npm run test:js:ci           

      - uses: actions/upload-artifact@v4  
        if: success() || failure()        
        with:
          name: test-results
          path: reports/jest-junit.xml